---
title: "Prediction"
output: html_document
---
Background

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset). 


Data 

The training data for this project are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv

The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment. 



First of all, it's necessary to look at our data.
```{r}
data <- read.csv("pml-training.csv")
## summary(data)
ncol(data)
```

There are 160 columns in our data.
What we are going to do, firstly, is to clean data. There are many columns with lots of NAs, we can't use these columns to fit the model.

After cleaning data, we need to choose which columns to fit the model. In this period, we can do some basic Preprocessing.

What's next, is to choose a prediction model. We can use Linear Regression model, regularized Linear Regression model, Artificial Neural Networks and etc.

Next, it's time to run the model with data. From the error, we can choose a best model.
